### ISSUE TITLE
finalspeed 连不上

### ISSUE THREAD

**Issue by oit63** [jonechenug/ss-finalspeed-docker#1]
我去Docker 里跑了一下
\ # sh fs_start.sh  
  FinalSpeed start,log file: /fs/server.log  
  fs_start.sh: 5: fs_start.sh: cannot create : Directory nonexistent  
\ # 

不知道什么原因，客户端一直连不上服务端。

**Comment by jonechenug** [comment]
finalspeed依赖于iptables和150端口，而在容器内又是另一个虚拟网络。我尝试在容器外运行iptables，然而并不能使用，所以可能要关闭该项目了。

**Comment by oit63** [comment]
恩，给容器开一个私有的150端口可行吗？

**Comment by jonechenug** [comment]
测试过不行（外部iptables允许150端口没试过），可能要容器内的iptables接管外部吧。

**Comment by oit63** [comment]
恩，finalSpeed 的速度确实快！不过我用挂在Banwagon的 finalSpeed UDP经常失效。。。DigitalOcean 的又不知道怎么搞的连不上服务器。。

**Comment by oit63** [comment]
它的Mac 客户端做得还不好，退出了以后经常需要删除了重新配置才又生效

**Comment by alienwaredream** [comment]
请问有没有finalspeed客户端在docker中运行的方法？

**Comment by jonechenug** [comment]
@alienwaredream finalspeed客户端应该更新了几个版本，最好是有命令版运行的，可以配置文件的话，可以考虑做一个。

**Comment by alienwaredream** [comment]
@jonechenug 有一个命令行版本，我在centos容器里部署成功了，但是我不知道怎么制作docker (/ □ )
地址是https://github.com/zqhong/finalspeed/releases 你可以看下吗？

**Comment by jonechenug** [comment]
@alienwaredream 我已经创建了一个[docker](https://github.com/jonechenug/finalspeed-client-docker)，部署在灵雀云上，然而有些错误可能需要你提供帮助。日志如下：

java.io.IOException: Cannot run program "iptables": error=2, No such file or directory
Caused by: java.io.IOException: error=2, No such file or directory
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

**Comment by alienwaredream** [comment]
我也有类似的错误日志
java.io.IOException: Cannot run program &quot;iptables&quot;: error=2, No such file or directory
stdout
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
stdout
    at java.lang.Runtime.exec(Runtime.java:620)
stdout
    at java.lang.Runtime.exec(Runtime.java:450)
stdout
    at java.lang.Runtime.exec(Runtime.java:388)
stdout
    at net.fs.client.MapClient.runCommand(MapClient.java:412)
stdout
    at net.fs.client.MapClient.setFireWallRule(MapClient.java:207)
stdout
    at net.fs.client.MapClient.setMapServer(MapClient.java:160)
stdout
    at net.fs.client.ClientNoUI.run(ClientNoUI.java:97)
stdout
    at net.fs.client.FSClient.main(FSClient.java:9)
但好像并不影响使用

有个疑问就是fs客户端的配置是写在clien_config.json和port_map.json两个文件中，请问这样的配置能用docker环境变量的方式输入么？还是只能写死，用vi编辑器进行修改？

**Comment by jonechenug** [comment]
@alienwaredream  参考我项目下的ssdocke是可以的，或者你可以直接使用bash来创建json，你确定可以使用吗？我之前在灵雀云上部署，连不上去。这阵子比较忙，过几天或者51的时候完善
